spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            #client-authentication-method:
            #authorization-grant-type:
          github:
            client-id:
            client-secret:
            #client-authentication-method:
            #authorization-grant-type:
  application:
    name: demo
